### PR TITLE
pass 'data' to parse_data() (fixes bug if data is named "i")

### LINKED ISSUE #654: data named “i” is overwritten by rstan
An anonymous user on discourse reported an error that i helped them work around, but is a bug in RStan:

https://discourse.mc-stan.org/t/mismatch-in-dimensionality-stan-is-fixing-the-dimensionality-to-a-number-why/9158

It seems that an integer (probably other types too) named `i` (lower case) in the list passed to `data` has its value overwritten when RStan processes/checks the data. The temporary workaround is for the user to just change the name from i to something else.

### PR DESCRIPTION
**Pull request by jgabry**
fixes #654

#### Summary:

Data named `i` was overwritten by RStan.

#### Intended Effect

Give `parse_data()` a data argument instead of using `with(data, ...)` in `sampling()`. And then use `mget()` instead of `dynGet()` inside of parse_data(). This avoid overwriting `i`, but it's unclear why it was being overwritten. See comments in #654. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

File: rstan/rstan/R/misc.R [hunk 1]
```diff
@@ -1602,10 +1602,17 @@ parse_data <- function(cppcode) {
...
+    # get them from the calling environment
+    stuff <- sapply(objects, simplify = FALSE, FUN = dynGet, 
+                    inherits = FALSE, ifnotfound = NULL) 
+  } else {
+    # get them from 'data', and we know already from sampling() and other
+    # methods that is.list(data) & !is.data.frame(data)
+    stuff <- mget(objects, envir = as.environment(data), inherits = FALSE,
+                  ifnotfound = rep(list(NULL), length(objects)))
+  }
   for (i in seq_along(stuff)) if (is.null(stuff[[i]])) {
```
Comment (bgoodri) [inline rstan/rstan/R/misc.R:1612]: I think this PR does too much when we (or at least I) don't remember what the side effects were of doing things differently than the way it is. I think we just need to change `for (i in seq_along(stuff))` to something not indexed by `i`. Ironically, `int` would work as an index variable because it cannot be used as a symbol name in a Stan program.

Comment (jgabry) [reply rstan/rstan/R/misc.R:1612]: I think it's more complicated than that. Before changing to use `mget` the value of `i` was already messed up in the `stuff` object _before_ it ever got to the loop part `for (i in seq_along(stuff)) ...`.

**Comment by bgoodri** [comment]
Then we must have another loop over i somewhere in scope.

**Comment by jgabry** [comment]
I assume so, but not it's not clear where. `parse_data` is called from the `sampling()` method which doesn't have an explicit loop over `i`. And neither does the `stan` function when it calls `sampling`.

**Comment by jgabry** [comment]
If I change `parse_data` to do the same thing in a loop that `sapply` was doing (and also use `int` instead of `i` to index) then it seems to be ok:

```r
# current method: stuff$i will have wrong value
  stuff <- sapply(objects, simplify = FALSE, FUN = dynGet, 
                  inherits = FALSE, ifnotfound = NULL)
```

```r
# stuff$i has correct value
  for (int in seq_along(objects)) {
   stuff[[objects[int]]] <- dynGet(objects[int], inherits = FALSE, ifnotfound = NULL)
  }
```

**Comment by bgoodri** [comment]
ok
