### PR TITLE
Make a temporary Makevars file when windows users have -march=native 

### LINKED ISSUE #801: Fixing Windows Compilation Errors
#### Summary:

I'm trying to sort out which Makevars flags we need to check / set for windows users.

#### Description:

In [this thread](https://discourse.mc-stan.org/t/error-running-stan-model-with-rstan-2-21-in-windows/16499/18?u=stevebronder) it was found that `-march=native` can cause compilation errors and crashes on windows because of a bug in msys's `g++` which does not allow for AVX instruction sets.

In order to make sure _windows_ users don't include `-march=native` I think what we want to do is

1. On startup scan through the `CXX*FLAGS` from all the makevars returned from `get_all_makefile_paths()`
2. If `-march=native` exists in one of these, suggest the user calls the function `rstan:::setup_makevar_files(overwrite = TRUE)` which will make a backup of the Makevar files, then remove `-march=native` from the file.

`setup_makevar_flags` can look like

```R
setup_makevar_flags <- function(overwrite = FALSE, optimized = FALSE) {
   if (overwrite) {
    # write Makevars.bak files, then remove -march=native if it exists for windows users
    if (optimized) {
      # add performance flags like O3, -mtune=native, the -m* flags for windows
    }
   } else {
     # read the Makevars and print a makevar with changes
    if (optimized) {
      # add performance flags like O3, -mtune=native, the -m* flags for windows
    }
   }
}
```

If we want to detect the CPU type for setting the windows `-m*` flags we could detect the CPU type with something like the below from `benchmarkme`

https://www.rdocumentation.org/packages/benchmarkme/versions/1.0.4/source

Reading through the flags, I thought we would just need to change `CXX14FLAGS` but looking at the compilation code it looks like rstan actually [uses `CXXFLAGS`](https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/cxxfunplus.R#L209). Should that change to 

```R
cxxflags <- try(get_makefile_flags("CXX14FLAGS"))
```

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Summary:

Fixes #801 by adding a function `.remove_march_makevars()` that in `cxxfunctionplus()` scrubs any `-march=native` from `CXX*FLAGS` in the users `MakeVars` if they are on a windows system.

#### Intended Effect:

This should stop crashes on windows from compiling with `-march=native`

#### How to Verify:

Running this on windows with `-march=native` should not show `-march=native` during compilation

```R
library(rstan)
stan(model_code = "// saved as schools.stan
  data {
    int<lower=0> J;         // number of schools 
    real y[J];              // estimated treatment effects
    real<lower=0> sigma[J]; // standard error of effect estimates 
  }
  parameters {
    real mu;                // population treatment effect
    real<lower=0> tau;      // standard deviation in treatment effects
    vector[J] eta;          // unscaled deviation from mu by school
  }
  transformed parameters {
    vector[J] theta = mu + tau * eta;        // school treatment effects
  }
  model {
    target += normal_lpdf(eta | 0, 1);       // prior log-density
    target += normal_lpdf(y | theta, sigma); // log-likelihood
  }", data = schools_dat, cores = 4, verbose = TRUE)
```

#### Side Effects:

This will make a temporary MakeVar that R references via `R_MAKEVARS_USER`. I am a bit worried this would stop users from using their own `withr::with_makevars` sort of like #427. We could just do this if we read the makevars and find `-march=native`

#### Documentation:

Docs added for internal functions

#### Reviewer Suggestions: 

I actually can't test this because I don't have a windows machine so if the reviewer can verify this solves issues on windows that would be cool

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by SteveBronder** [comment]
For the jenkins

```
> install.packages("devtools", repos = "https://cran.r-project.org")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages("devtools", repos = "https://cran.r-project.org") :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages("devtools", repos = "https://cran.r-project.org") : 
  unable to install packages
```

Is that a me thing or Jenkins thing?

**Comment by SteveBronder** [comment]
Also should there be something in rstan's compilation that checks whether the `CXXFLAGS` has `-march=native` as well and throw a meaningful error message there?

**Comment by jgabry** [comment]
@bgoodri have you seen this yet? we should really release asap this if it looks ok, since rstan is still broken with our previously recommended windows setup, right?

File: rstan/rstan/R/makefile_op.R [hunk 1]
```diff
@@ -200,3 +200,73 @@ rm_rstan_makefile_flags <- function() {
...
+  makevars_file <- tempfile()
+  setup_makevar <- function(state) {
+    withr::set_makevars(new, path, state, assignment = assignment)
+    old <- .set_enviro_var(envs = c(R_MAKEVARS_USER = state), action = "replace")
+    withr::defer(.set_enviro_var(old), envir = local_env)
+    invisible(old)
+  }
+  cleanup_makevar <- function(state) {
+    unlink(state)
+    Sys.unsetenv(R_MAKEVARS_USER)
```
Comment (bgoodri) [inline rstan/rstan/R/makefile_op.R]: If the user has set `R_MAKEVARS_USER` to be something other than `""` or `~/.R/Makevars{.win}`, then this will cause it to be unset for the rest of the R session. I think we need to do `RMU <- Sys.getenv(R_MAKEVARS_USER)` and the top of the `.local_makevars` function and call `Sys.setenv(R_MAKEVARS_USER = RMU)` inside `cleanup_makevar`.

File: rstan/rstan/R/makefile_op.R [hunk 2]
```diff
@@ -200,3 +200,73 @@ rm_rstan_makefile_flags <- function() {
...
+  }
+  return(withr::local_(setup_makevar, cleanup_makevar)(makevars_file))
+}
+
+
+#' Remove march flag from Makevars
+.remove_march_makevars <- function() {
+  makevar_files <- withr::makevars_user()
+  cxx_flags <- grep("^CXX.*FLAGS", readLines(file.path(makevar_files)), value = TRUE)
+  trimmed_flag <- trimws(gsub("-march=native", "", substr(cxx_flags, regexpr("-", cxx_flags), nchar(cxx_flags))))
```
Comment (bgoodri) [inline rstan/rstan/R/makefile_op.R]: That should be `gsub("-march[[:space:]]*=[[:space:]]*native", ...)`

File: rstan/rstan/R/makefile_op.R [hunk 3]
```diff
@@ -200,3 +200,73 @@ rm_rstan_makefile_flags <- function() {
...
+#'  @note Has the same behavior as `withr::with_makevars` but closes the 
+#'   temporary makevar file after the result object leaves scope.
+#'  @param new a named vector of names and values to assign to the makevars values.
+#'  @param path Path to Makevars. By default is `withr::makevars_user()`.
+#'  @param assignment Assignment type to use.
+#'  @param local_env The environment that when exited will cleanup the temp Makevars.
+.local_makevars <- function(new, path = withr::makevars_user(),
+                            assignment = c("=", ":=", "?=", "+="), local_env = parent.frame()) {
+  assignment <- match.arg(assignment)
+  makevars_file <- tempfile()
```
Comment (bgoodri) [inline rstan/rstan/R/makefile_op.R]: I would go with `makevars_file <- tempfile(pattern = "Makevars")` so that someone can know what file to look for in `tempdir` if something goes wrong.

**Comment by SteveBronder** [comment]
Cool cool @bgoodri fixed up stuff
